settings/urls.py
from django.conf.urls import url
from . import views

app_name = 'settings'

urlpatterns = [
	url(r'^commodities$', views.editCommodities, name='editCommodities'),
	url(r'^minePlan$', views.editMinePlan, name='editMinePlan'),
	url(r'^products$', views.editProject, name='editProject'),
    url(r'^(?i)CAPEX$', views.editCAPEX, name='editCAPEX'),
    url(r'^(?i)OPEX$', views.editOPEX, name='editOPEX'),
	url(r'^smelter$', views.editSmelter, name='editSmelter'),
	url(r'^prices$', views.editPrices, name='editPrices'),
	url(r'^inputs$', views.editInputs, name='editInputs'),
]

settings/templates/settings/commodity.html
{% include "home/header.html" %}

<form class="form-signup" role="form" action="{% url 'settings:editCommodities' %}" method="POST">

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

				<center>
		        <h2 class="form-signup-heading">Selected Main Commodities:</h2>
		        </center>
		        <br>

		        {% if errorMsg != None %}
		        	<center>
		        	<p class="errorMsg" style="color:#FF6600">{{ errorMsg }}</p>
		        	</center>
		        {% endif %}
		        
		        {% csrf_token %}

		</div>

		<div class="col-sm-4">
		</div>

	</div>


	<div class="row">

		<div class="col-sm-4">
		<ul style="list-style: none;" id="id_{{ form.mainCommodity1.name }}">
 			{% for pk, choice in form.mainCommodity1.field.widget.choices %}
				<li>
					<label for="id_{{ form.mainCommodity1.name }}_{{ forloop.counter0 }}">
						<input {% for option in form.mainCommodity1.field.initial %}{% if option == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.mainCommodity1.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.mainCommodity1.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</div>
	

		<div class="col-sm-4">
		<ul style="list-style: none;" id="id_{{ form.mainCommodity2.name }}">
 			{% for pk, choice in form.mainCommodity2.field.widget.choices %}
				<li>
					<label for="id_{{ form.mainCommodity2.name }}_{{ forloop.counter0 }}">
						<input {% for option in form.mainCommodity2.field.initial %}{% if option == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.mainCommodity2.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.mainCommodity2.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</div>

		<div class="col-sm-4">
		<ul style="list-style: none;" id="id_{{ form.mainCommodity3.name }}">
 			{% for pk, choice in form.mainCommodity3.field.widget.choices %}
				<li>
					<label for="id_{{ form.mainCommodity3.name }}_{{ forloop.counter0 }}">
						<input {% for option in form.mainCommodity3.field.initial %}{% if option == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.mainCommodity3.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.mainCommodity3.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</div>

	</div>



	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<!-- <form class="form-signup" role="form" action="{% url 'setup:index' %}" method="POST"> -->
				<center>
		        <h2 class="form-signup-heading">Selected Deleterious Commodities:</h2>
		        </center>
		        <br>

		</div>

		<div class="col-sm-4">
		</div>

	</div>


	<div class="row">

		<div class="col-sm-4">
		<ul style="list-style: none;" id="id_{{ form.delCommodity1.name }}">
 			{% for pk, choice in form.delCommodity1.field.widget.choices %}
				<li>
					<label for="id_{{ form.delCommodity1.name }}_{{ forloop.counter0 }}">
						<input {% for option in form.delCommodity1.field.initial %}{% if option == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.delCommodity1.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.delCommodity1.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</div>

		<div class="col-sm-4">
		<ul style="list-style: none;" id="id_{{ form.delCommodity2.name }}">
 			{% for pk, choice in form.delCommodity2.field.widget.choices %}
				<li>
					<label for="id_{{ form.delCommodity2.name }}_{{ forloop.counter0 }}">
						<input {% for option in form.delCommodity2.field.initial %}{% if option == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.delCommodity2.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.delCommodity2.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</div>

		<div class="col-sm-4">
		<ul style="list-style: none;" id="id_{{ form.delCommodity3.name }}">
 			{% for pk, choice in form.delCommodity3.field.widget.choices %}

				<li>
					<label for="id_{{ form.delCommodity3.name }}_{{ forloop.counter0 }}">
						<input {% for option in form.delCommodity3.field.initial %}{% if option == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.delCommodity3.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.delCommodity3.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</div>

	</div>



	<div class="row">

		<div class="col-sm-4">
		</div>

		<center>
		<div class="col-sm-4">
			<button class="btn btn-group-lg btn-primary" type="button" onClick="location.href='{% url 'home:index' %}'">Cancel</button>
			<!-- <button class="btn btn-lg btn-primary btn-block" type="submit">Next</button> -->
			</form>
			<!-- <button class="btn btn-lg btn-primary btn-block" type="button">Back</button> -->
		</div>
		</center>

		<div class="col-sm-4">
		</div>

	</div>

	<br>
	<br>

{% include "home/footer.html" %}

settings/templates/settings/inputs.html
{% include "home/header.html" %}

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<form class="form-signup" role="form" action="{% url 'settings:editInputs' %}" method="POST">
				<center>
		        <h2 class="form-signup-heading">Declare Inputs:</h2>
		        </center>
		        <br>
		        {% csrf_token %}

				<div class="table-responsive">
					<table class="table table-condensed">
					{{ form.as_table }}
					</table>
				</div>

			<center>
			<button class="btn btn-group-lg btn-primary" type="button" onClick="location.href='{% url 'home:index' %}'">Cancel</button>
			<button class="btn btn-group-lg btn-primary" type="submit">Save Changes</button>
			</form>
			</center>

		</div>

		<div class="col-sm-4">
		</div>

	</div>

{% include "home/footer.html" %}

settings/templates/settings/mineProduction.html
{% include "home/header.html" %}
{% load index %}
{% load get_item %}

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<form class="form-signup" role="form" action="{% url 'settings:editMinePlan' %}" method="POST">
				<center>
		        <h2 class="form-signup-heading">Mine Production:</h2>
		        </center>
		        <br>
		        {% csrf_token %}

		        <br>
				<br>

		</div>

		<div class="col-sm-4">
		</div>

	</div>

	<div class="table-responsive">
  		<table class="table table-bordered">
    		<thead> 
    			<tr> 
    				<th>Mine Plan Tonnage</th>
    				{% for year in LOM %}
    					<th>Year {{ year }}</th>
    				{% endfor %}
    			</tr> 
    		</thead>
    		<tbody>

            {% for curr in numStockpiles %}
                <tr>
                    <th>Stockpile {{ curr }}</th>
                    {% for year in LOM %}
                        <td><input id="id_year{{ year }}MinePlanStockpile{{curr}}Tonnage" name="year{{ year }}MinePlanStockpile{{curr}}Tonnage" placeholder="Max 2 Decimals" step="0.01" type="number" value='{{ minePlanTonnages|get_item:curr|get_item:year }}' required=""></td>
                    {% endfor %}
                </tr>
            {% endfor %}

    		</tbody>
  		</table>

        <table class="table table-bordered">
            <thead> 
                <tr>
                    <th>Mine Plan Grade</th>
                    {% for year in LOM %}
                        <th>Year {{ year }}</th>
                    {% endfor %}
                </tr> 
            </thead>
            <tbody>

                {% for curr in numStockpiles %}
                    {% for name in commNameList %}
                        <tr>
                            <th>Stockpile {{ curr }} {{ name }} (%)</th>
                            {% for year in LOM %}
                                <td><input id="id_year{{ year }}MinePlanSP{{ curr }}Grade{{ name }}" name="year{{ year }}MinePlanSP{{ curr }}Grade{{ name }}" placeholder="Max 6 Decimals" step="0.000001" type="number" value="{{ minePlanGrades|get_item:curr|get_item:name|get_item:year }}" required=""></td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                {% endfor %}

            </tbody>
        </table>
	</div>

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class="col-sm-4">
			<center>
			<button class="btn btn-group-lg btn-primary" type="button" onClick="location.href='{% url 'home:index' %}'">Cancel</button>
			<button class="btn btn-group-lg btn-primary" type="submit">Save Changes</button>
			</form>
			</center>
			
		</div>
	

		<div class="col-sm-4">
		</div>

	</div>
    <br>

{% include "home/footer.html" %}

settings/templates/settings/opex.html
{% include "home/header.html" %}
{% load index %}

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<form class="form-signup" role="form" action="{% url 'settings:editOPEX' %}" method="POST">
				<center>
		        <h2 class="form-signup-heading">Edit OPEX (in CAD$):</h2>
		        </center>
		        <br>
		        {% csrf_token %}

				<input type="hidden" value="{{ LOM }}" name="LOM" />

		        <br>
				<br>

		</div>

		<div class="col-sm-4">
		</div>

	</div>

	<div class="table-responsive">
  		<table class="table table-bordered">
    		<thead> 
    			<tr> 
    				<th>        </th>
    				{% for i in "x"|rjust:LOM %}
    					<th>Year {{ forloop.counter0|add:"1" }}</th>
    				{% endfor %}
    			</tr> 
    		</thead>
    		<tbody>
    			<tr>
    				<th>Mining</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}Mining" name="year{{ forloop.counter0|add:'1' }}Mining" placeholder="Max 2 Decimals" step="0.01" type="number" {% if mining|index:forloop.counter0 is not None %} value="{{ mining|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Infrastructure</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}Infrastructure" name="year{{ forloop.counter0|add:'1' }}Infrastructure" placeholder="Max 2 Decimals" step="0.01" type="number" {% if infrastructure|index:forloop.counter0 is not None %} value="{{ infrastructure|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Stockpile LG</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}StockpileLG" name="year{{ forloop.counter0|add:'1' }}StockpileLG" placeholder="Max 2 Decimals" step="0.01" type="number" {% if stockpileLG|index:forloop.counter0 is not None %} value="{{ stockpileLG|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Dewatering</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}Dewatering" name="year{{ forloop.counter0|add:'1' }}Dewatering" placeholder="Max 2 Decimals" step="0.01" type="number" {% if dewatering|index:forloop.counter0 is not None %} value="{{ dewatering|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Processing</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}Processing" name="year{{ forloop.counter0|add:'1' }}Processing" placeholder="Max 2 Decimals" step="0.01" type="number" {% if processing|index:forloop.counter0 is not None %} value="{{ processing|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Product Hauling</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}ProductHauling" name="year{{ forloop.counter0|add:'1' }}ProductHauling" placeholder="Max 2 Decimals" step="0.01" type="number" {% if hauling|index:forloop.counter0 is not None %} value="{{ hauling|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Load-out and Rail Loop</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}LoadoutRailLoop" name="year{{ forloop.counter0|add:'1' }}LoadoutRailLoop" placeholder="Max 2 Decimals" step="0.01" type="number" {% if loadOutRailLoop|index:forloop.counter0 is not None %} value="{{ loadOutRailLoop|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>G&amp;A Site</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}GASite" name="year{{ forloop.counter0|add:'1' }}GASite" placeholder="Max 2 Decimals" step="0.01" type="number" {% if GASite|index:forloop.counter0 is not None %} value="{{ GASite|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>G&amp;A (Room &amp; Board and FIFO)</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}GARoomBoardFIFO" name="year{{ forloop.counter0|add:'1' }}GARoomBoardFIFO" placeholder="Max 2 Decimals" step="0.01" type="number" {% if GARoomBoardFIFO|index:forloop.counter0 is not None %} value="{{ GARoomBoardFIFO|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Rail Transportation</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}RailTransportation" name="year{{ forloop.counter0|add:'1' }}RailTransportation" placeholder="Max 2 Decimals" step="0.01" type="number" {% if railTransport|index:forloop.counter0 is not None %} value="{{ railTransport|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>G&amp;A (Corporate)</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}GACorporate" name="year{{ forloop.counter0|add:'1' }}GACorporate" placeholder="Max 2 Decimals" step="0.01" type="number" {% if GACorp|index:forloop.counter0 is not None %} value="{{ GACorp|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Royalties</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}Royalties" name="year{{ forloop.counter0|add:'1' }}Royalties" placeholder="Max 2 Decimals" step="0.01" type="number" {% if royalties|index:forloop.counter0 is not None %} value="{{ royalties|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Transportation</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}Transportation" name="year{{ forloop.counter0|add:'1' }}Transportation" placeholder="Max 2 Decimals" step="0.01" type="number" {% if transportation|index:forloop.counter0 is not None %} value="{{ transportation|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>G&amp;A</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}GA" name="year{{ forloop.counter0|add:'1' }}GA" placeholder="Max 2 Decimals" step="0.01" type="number" {% if GA|index:forloop.counter0 is not None %} value="{{ GA|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Shipping Cost</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}ShippingCost" name="year{{ forloop.counter0|add:'1' }}ShippingCost" placeholder="Max 2 Decimals" step="0.01" type="number" {% if shipping|index:forloop.counter0 is not None %} value="{{ shipping|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
                        </td>
    				{% endfor %}
    			</tr>
				<tr>
    				<th>OPEX (CAD$/t)</th>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}OpexPT" name="year{{ forloop.counter0|add:'1' }}OpexPT" placeholder="Max 2 Decimals" step="0.01" type="number" {% if opexPT|index:forloop.counter0 is not None %} value="{{ opexPT|index:forloop.counter0|floatformat:'-2' }}" {% endif %}>
						</td>
    				{% endfor %}
    			</tr>
    		</tbody>
  		</table>
	</div>

	<div class="row">
		<div class="col-sm-4">
		</div>

		<div class="col-sm-4">
            <center>
            <button class="btn btn-group-lg btn-primary" type="button" onClick="location.href='{% url 'home:index' %}'">Cancel</button>
            <button class="btn btn-group-lg btn-primary" type="submit">Save Changes</button>
            </form>
            </center>
		</div>

		<div class="col-sm-4">
		</div>
	</div>

	<p></p>

{% include "home/footer.html" %}

settings/templates/settings/prices.html
{% include "home/header.html" %}
{% load get_item %}
{% load ifinlist %}


	<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">
			<br>
			<br>

			<form class="form-signup" role="form" action="{% url 'settings:editPrices' %}" method="POST">
				<center>
		        <h2 class="form-signup-heading">Edit Prices (US$/t):</h2>
		        </center>
		        <br>
		        {% csrf_token %}

				<div class="table-responsive">
					<table class="table table-bordered">
						<thead> 
                			<tr> 
                    			<th>        </th>
                    			{% if 1|ifinlist:PPIDs %}
                    			<th>Lump Price</th>
                    			<th>Lump Premium</th>
                    			{% endif %}
                    			{% if 2|ifinlist:PPIDs %}
                    			<th>Fines Price</th>
                    			{% endif %}
                    			{% if 3|ifinlist:PPIDs %}
                    			<th>Ultra Fines Price</th>
                    			{% endif %}
                    			{% if 1|ifinlist:PPIDs %}
                    			<th>Lump Average</th>
                    			{% endif %}
                			</tr> 
           				</thead>
           				<tbody>
           				{% for curr in numStockpiles %}
           					<tr>
           						<th>Stockpile {{ curr }}</th>
           						{% if 1|ifinlist:PPIDs %}
           						<td>
           							<input id="id_Stockpile{{ curr }}Lump" name="Stockpile{{ curr }}Lump" placeholder="Max 2 Decmial Places" step="0.01" type="number" value="{{ lumps|get_item:curr }}" required="">
           						</td>
	           					<td>
	           						<input id="id_Stockpile{{ curr }}LumpPrem" name="Stockpile{{ curr }}LumpPrem" placeholder="Max 2 Decmial Places" step="0.01" type="number" value="{{ lumpPrems|get_item:curr }}" required="">
	           					</td>
	           					{% endif %}
	           					{% if 2|ifinlist:PPIDs %}
	           					<td>
	           						<input id="id_Stockpile{{ curr }}Fines" name="Stockpile{{ curr }}Fines" placeholder="Max 2 Decmial Places" step="0.01" type="number" value="{{ fines|get_item:curr }}" required="">
	           					</td>
	           					{% endif %}
	           					{% if 3|ifinlist:PPIDs %}
	           					<td>
	           						<input id="id_Stockpile{{ curr }}UltraFines" name="Stockpile{{ curr }}UltraFines" placeholder="Max 2 Decmial Places" step="0.01" type="number" value="{{ ultraFines|get_item:curr }}" required="">
	           					</td>
	           					{% endif %}
	           					{% if 1|ifinlist:PPIDs %}
	           					<td>
	           						<input id="id_Stockpile{{ curr }}LumpAvg" name="Stockpile{{ curr }}LumpAvg" placeholder="Max 2 Decmial Places" step="0.01" type="number" value="{{ lumpAvgs|get_item:curr }}" required="">
	           					</td>
	           					{% endif %}
           					</tr>
           				{% endfor %}	
           				</tbody>
					</table>
				</div>

				<center>
				<button class="btn btn-group-lg btn-primary" type="button" onClick="location.href='{% url 'home:index' %}'">Cancel</button>
				<button class="btn btn-group-lg btn-primary" type="submit">Save Changes</button>
				</form>
				</center>
			</form>
		 
		</div>

		<div class="col-sm-2">
		</div>

	</div>



{% include "home/footer.html" %}

settings/templates/settings/products.html
{% include "home/header.html" %}

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<form class="form-signup" role="form" action="{% url 'settings:editProject' %}" method="POST">
				<center>
		        <h2 class="form-signup-heading">View Products:</h2>
		        </center>
		        <br>

		        {% if errorMsg != None %}
		        	<center>
		        	<p>{{ errorMsg }}</p>
		        	</center>
		        {% endif %}
		        
		        {% csrf_token %}

				<p>
					<label for="id_{{ form.projectType.name }}">{{ form.projectType.label }}:</label>
					<select class="form-control" id="id_{{ form.projectType.name }}" name="{{ form.projectType.name }}" required>
						{% for pk, choice in form.projectType.field.widget.choices %}
							<option value="{{ pk }}" {% if form.projectType.field.initial == pk %}selected{% endif %}>{{ choice }}</option>
						{% endfor %}
					</select>
				</p>

				<p>
					<label for="id_{{ form.mineProduct.name }}">{{ form.mineProduct.label }}:</label>
					<ul style="list-style: none;" id="id_{{ form.mineProduct.name }}">
 						{% for pk, choice in form.mineProduct.field.widget.choices %}
							<li>
								<label for="id_{{ form.mineProduct.name }}_{{ forloop.counter0 }}">
								<input {% for option in form.mineProduct.field.initial %}{% if option == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.mineProduct.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.mineProduct.name }}" />
								{{ choice }}
								</label>
							</li>
						{% endfor %}
					</ul>
				</p>

				<p>
					<label for="id_{{ form.plantProduct.name }}">{{ form.plantProduct.label }}:</label>
					<ul style="list-style: none;" id="id_{{ form.plantProduct.name }}">
 						{% for pk, choice in form.plantProduct.field.widget.choices %}
							<li>
								<label for="id_{{ form.plantProduct.name }}_{{ forloop.counter0 }}">
								<input {% for option in form.plantProduct.field.initial %}{% if option == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.plantProduct.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.plantProduct.name }}" />
								{{ choice }}
								</label>
							</li>
						{% endfor %}
					</ul>
				</p>

				<p>
					<label for="id_{{ form.LOM.name }}">{{ form.LOM.label }}:</label>
					<input class="form-control" id="id_{{ form.LOM.name }}" name="{{ form.LOM.name }}" min="{{ form.LOM.field.min_value }}" type="number" value="{{ form.LOM.field.initial }}" required>
				</p>

<!-- 				{{ form.as_p }} -->

		    <center>
			<button class="btn btn-group-lg btn-primary" type="button" onClick="location.href='{% url 'home:index' %}'">Cancel</button>
			<!-- <button class="btn btn-group-lg btn-primary" type="submit">Save Changes</button> -->
			</form>
			</center>

		</div>

		<div class="col-sm-4">
		</div>

	</div>
	<br>
	<br>

{% include "home/footer.html" %}

settings/templates/settings/success.html
{% include "home/header.html" %}

<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">
			<center>
		        <h2>Update Success!</h2>
		    </center>
		    <center>
		    <a href="/home">Return to Homepage</a>
		    </center>
		</div>

		<div class="col-sm-2">
		</div>

</div>

{% include "home/footer.html" %}