login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^PasswordReset$', views.passwordReset, name='passwordReset'),
	url(r'^PasswordResetActivation$', views.passwordResetActivation, name='passwordResetActivation'),
	url(r'^ConfirmPassword$', views.confirmPassword, name='confirmPassword')
]

login/models.py
from django.db import models

# Create your models here.
class tblCompany(models.Model):
	companyID = models.AutoField(primary_key=True)
	company = models.CharField(max_length=250)
	address = models.CharField(max_length=250)
	city = models.CharField(max_length=100)
	province = models.CharField(max_length=50)
	country = models.CharField(max_length=50)
	postalCode = models.CharField(max_length=10)
	phone = models.CharField(max_length=32)
	# dateAdded = models.DateTimeField(auto_now_add=True)
	dateAdded = models.DateTimeField(null=False)

	def __str__(self):
		return str(self.companyID)

	class Meta:
		db_table = 'tblCompany'

class tblMine(models.Model):
	mineID = models.AutoField(primary_key=True)
	mine = models.CharField(max_length=100)
	address = models.CharField(max_length=250)
	city = models.CharField(max_length=100)
	province = models.CharField(max_length=50)
	country = models.CharField(max_length=50)
	postalCode = models.CharField(max_length=10)
	phone = models.CharField(max_length=32)
	dateAdded = models.DateTimeField(null=False)

	def __str__(self):
		return str(self.mineID)

	class Meta:
		db_table = 'tblMine'

class tblUsers(models.Model):
	userID = models.AutoField(primary_key=True)
	mineID = models.ForeignKey('tblMine', db_column='mineID')
	companyID = models.ForeignKey('tblCompany', db_column='companyID')
	username = models.CharField(max_length=50, unique=True)
	firstName = models.CharField(max_length=50)
	lastName = models.CharField(max_length=50)
	email = models.CharField(max_length=100)
	phone = models.CharField(max_length=32)
	jobTitle = models.CharField(max_length=50)

	# Need to change userRole settings
	userRole = models.IntegerField()

	password = models.CharField(max_length=64)
	lastLogin = models.DateTimeField()
	dateAdded = models.DateTimeField(null=False)

	def __str__(self):
		return str(self.userID)

	class Meta:
		db_table = 'tblUsers'

login/forms.py
from django import forms

class loginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=50)
	password = forms.CharField(label='Password',
		widget=forms.PasswordInput, max_length=50)

class passwordResetForm(forms.Form):
	email = forms.CharField(label='Enter Your Email', max_length=100)

class passwordResetActivationForm(forms.Form):
	email = forms.CharField(label='Your Email Address', max_length=100)
	activationCode = forms.CharField(label='Reset Activation Code', max_length=100)

class confirmPasswordForm(forms.Form):
	newPW = forms.CharField(label='Enter Your New Password',
		widget=forms.PasswordInput, max_length=50)
	confirmPW = forms.CharField(label='Confirm Password',
		widget=forms.PasswordInput, max_length=50)

login/views.py
from django.shortcuts import render
from django.utils import timezone
from datetime import timedelta

from .forms import *
from setup.models import tblUsers
import random, string

from django.conf import settings
from django.core.mail import send_mail

# Create your views here.
def index(request):
	# return render(request, 'login/login.html')
	form_class = loginForm
	if request.method == 'POST':

		form = loginForm(request.POST)

		if form.is_valid():
			# company = request.POST.get('companyName', '')
			# address = request.POST.get('address', '')
			# city = request.POST.get('city', '')
			# province = request.POST.get('province', '')
			# country = request.POST.get('country', '')
			# postalCode = request.POST.get('postalCode', '')
			# phone = request.POST.get('phone', '')
			# dateAdded = timezone.localtime(timezone.now())

			username = request.POST.get('username', '')
			password = request.POST.get('password', '')

			# Check username exists
			try:
				match = tblUsers.objects.get(username=username)
			except tblUsers.DoesNotExist:
				match = None
			if (match is None):
				return render(request, "login/login.html", {'form': form_class,
					'errorMsg': 'Login credentials incorrect. Please try again.'})

			# Next, password verification
			if (password != match.password):
				return render(request, "login/login.html", {'form': form_class,
					'errorMsg': 'Login credentials incorrect. Please try again.'})

			# Getting here means password verified.
			# Update last login timestamp.
			# Establish an active session with this account.
			match.lastLogin = timezone.localtime(timezone.now())
			match.save()

			request.session['username'] = match.username
			request.session['firstname'] = match.firstName
			request.session['userID'] = str(match.userID)
			request.session['mineID'] = str(match.mineID)
			request.session.set_expiry(0)

			return render(request, 'login/success.html', { }) #Redirect

		form_class = loginForm
		return render_to_response("login/login.html", {'form': form_class})

	else:
		return render(request, "login/login.html", {'form': form_class})


def passwordReset(request):
	form_class = passwordResetForm
	if request.method == "POST":
		form = passwordResetForm(request.POST)

		if form.is_valid():
			email = request.POST.get('email', '')

			# Check email exists
			try:
				match = tblUsers.objects.get(email=email)
			except tblUsers.DoesNotExist:
				match = None
			if (match is None):
				return render(request, "login/passwordReset.html", {'form': form_class,
					'errorMsg': 'No account associated with this email was found. Please try again.'})

			resetCode = ''.join(random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits) for _ in range(6))
			resetExpiry = timezone.localtime(timezone.now()) + timedelta(days=3)

			host = request.get_host()
			firstName = match.firstName
			msgRecipients = [match.email]
			msgSender = "admin@magemi.com"
			msgSubject = "Magemi Mine Optimizer: Account Password Reset"
			msgBody = "Hi, " + firstName + ". We have received your password reset request. Your 6-digit activation code is " + resetCode + ". Please click here to begin the reset process: http://" + host + "/PasswordResetActivation" + "\n\nYour activation code expires in 3 days."

			match.reset = resetCode
			match.resetExpiry = resetExpiry
			match.save()

			send_mail(msgSubject, msgBody, settings.DEFAULT_FROM_EMAIL, msgRecipients, fail_silently=False)
			return render(request, "login/passwordEmailSent.html", {})
	else:
		return render(request, "login/passwordReset.html", {'form': form_class})


def passwordResetActivation(request):
	if request.method == "POST":
		form = passwordResetActivationForm(request.POST)
		if form.is_valid():
			email = request.POST.get('email', '')
			activationCode = request.POST.get('activationCode', '')

			# Check email exists
			try:
				match = tblUsers.objects.get(email=email)
			except tblUsers.DoesNotExist:
				match = None
			if (match is None):
				return render(request, "login/passwordResetActivation.html", {'form': form_class,
					'errorMsg': 'No account associated with this email was found. Please try again.'})

			# Check activation code is correct
			if match.reset != activationCode:
				return render(request, "login/passwordResetActivation.html", {'form': form_class,
					'errorMsg': 'Activation Code incorrect. Please try again.'})

			# Check activation code has not expired
			if match.resetExpiry < timezone.localtime(timezone.now()):
				return render(request, "login/passwordResetActivation.html", {'form': form_class,
					'errorMsg': 'Your activation code has expired. Please request for another password reset.'})

			form_class = confirmPasswordForm
			return render(request, "login/confirmPassword.html", {'form': form_class, 'email': email})
	else:
		form_class = passwordResetActivationForm
		return render(request, "login/passwordResetActivation.html", {'form': form_class})

def confirmPassword(request):
	form_class = confirmPasswordForm
	if request.method == "POST":
		form = confirmPasswordForm(request.POST)

		if form.is_valid():
			newPW = request.POST.get('newPW', '')
			confirmPW = request.POST.get('confirmPW', '')
			email = request.POST.get('email', '')

			# Check password and confirmPW fields are equal
			if newPW != confirmPW:
				return render(request, "login/confirmPassword.html", {'form': form_class,
					'errorMsg': 'Password and Confirm Password fields did not match. Please try again.',
					'email': email})

			match = tblUsers.objects.get(email=email)
			match.password = newPW
			match.save()

			return render(request, 'login/confirmPasswordSuccess.html', { }) #Redirect
	else:
		return render(request, 'login/confirmPassword.html', {'form': form_class})

login/templates/login/confirmPassword.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Magemi Mine Optimizer</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type = "text/css"/>
	<!--<meta name="viewport" content = "width=device-width, initial-scale=1.0">-->
	<meta name="viewport">
	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#FF6600" style="padding:40px">
<style="background-color:#FF6600">

{% if email is not None %}

	<center>
	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

		      <form class="form-signin" role="form" action="{% url 'login:confirmPassword' %}" method="POST">
					{% csrf_token %}
					<center>
			        <h2 class="form-signup-heading" style="color:#FFF">Password Reset</h2>
			        </center>
			        <br>

			        {% if errorMsg != None %}
			        	<center>
			        	<p>{{ errorMsg }}</p>
			        	</center>
			        {% endif %}

			        {% for field in form %}

					    <label class="sr-only" for="id_{{ field.name }}" hidden>{{ field.label }}</label>
					    <input class="form-control"
					    	{% if field.field.widget.input_type == "password" %}
					    		type="password"
					    	{% else %}
					    		type="text"
					    	{% endif %}
					        placeholder="{{ field.label }}"
					        id="{{ field.name }}"
					        name="{{ field.name }}"
					        maxlength="{{ field.field.max_length }}"
					        {% if field.field.required %}
					        	required
					        {% endif %}
						> 

					{% endfor %}

					<input type="hidden" name="email" value={{ email }}>

			        <br>
			        <button class="btn btn-lg btn-primary btn-block" type="submit">Confirm New Password</button>
			    </form>

		      <br>
			  
		      <center>
		      	<a href="/" style="color:#FFF" style="font-size:1.5em" >Cancel</a>
		      </center>
			  

		</div>

		<div class="col-sm-4">
		</div>

	</div>
	</center>

{% else %}

	<center>
	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<h2 class="form-signup-heading" style="color:#FFF">ERROR!</h2>

			<br>
			<center>
		      	<a href="/" style="color:#FFF" style="font-size:1.5em" >Home</a>
		    </center>
		    
{% endif %}

login/templates/login/confirmPasswordSuccess.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Magemi Mine Optimizer</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type = "text/css"/>
	<!--<meta name="viewport" content = "width=device-width, initial-scale=1.0">-->
	<meta name="viewport">
	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#FF6600" style="padding:40px">
<style="background-color:#FF6600">

	<center>
		<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">
			<center>
		        <h2>Your password has been reset.</h2>
		    </center>
		    <center>
		    <a href="/">Return to Homepage</a>
		    </center>
		</div>

		<div class="col-sm-2">
		</div>

		</div>
	</center>

login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Magemi Mine Optimizer</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type = "text/css"/>
	<!--<meta name="viewport" content = "width=device-width, initial-scale=1.0">-->
	<meta name="viewport">
	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#FF6600" style="padding:40px">
<style="background-color:#FF6600">

<center>
<div class="row">

	<div class="col-sm-4">
	</div>

	<div class='col-sm-4'>
		<br>
		<br>

	      <form class="form-signin" role="form" action="{% url 'login:index' %}" method="POST">
				{% csrf_token %}
				<center>
		        <h2 class="form-signup-heading" style="color:#FFF">Login Here</h2>
		        </center>
		        <br>

		        {% if errorMsg != None %}
		        	<center>
		        	<p>{{ errorMsg }}</p>
		        	</center>
		        {% endif %}

		        {% for field in form %}

				    <label class="sr-only" for="id_{{ field.name }}" hidden>{{ field.label }}</label>
				    <input class="form-control"
				    	{% if field.field.widget.input_type == "password" %}
				    		type="password"
				    	{% else %}
				    		type="text"
				    	{% endif %}
				        placeholder="{{ field.label }}"
				        id="{{ field.name }}"
				        name="{{ field.name }}"
				        maxlength="{{ field.field.max_length }}"
				        {% if field.field.required %}
				        	required
				        {% endif %}
					> 

				{% endfor %}

		        <br>
		        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
		    </form>

	      <br>
		  
		  <center>
	      <a href="/PasswordReset" style="color:#FFF" style="font-size:1.5em" >Reset your password</a>
	      </center>
		  
	      <!-- <center>
	      <a href="/signup" style="color:#FFF" style="font-size:1.5em" >Create an account</a>
	      </center> -->
		  

	</div>

	<div class="col-sm-4">
	</div>

</div>
</center>

login/templates/login/passwordEmailSent.html
{% include "home/header.html" %}

<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">
			<center>
		        <h2>Password reset email has been sent to your associated email account. Please follow the instructions.</h2>
		    </center>
		    <center>
		    <a href="/">Return to Login Page</a>
		    </center>
		</div>

		<div class="col-sm-2">
		</div>

</div>

{% include "home/footer.html" %}

login/templates/login/passwordReset.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Magemi Mine Optimizer</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type = "text/css"/>
	<!--<meta name="viewport" content = "width=device-width, initial-scale=1.0">-->
	<meta name="viewport">
	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#FF6600" style="padding:40px">
<style="background-color:#FF6600">

<center>
<div class="row">

	<div class="col-sm-4">
	</div>

	<div class='col-sm-4'>
		<br>
		<br>

	      <form class="form-signin" role="form" action="{% url 'login:passwordReset' %}" method="POST">
				{% csrf_token %}
				<center>
		        <h2 class="form-signup-heading" style="color:#FFF">Password Reset</h2>
		        </center>
		        <br>

		        {% if errorMsg != None %}
		        	<center>
		        	<p>{{ errorMsg }}</p>
		        	</center>
		        {% endif %}

		        {% for field in form %}

				    <label class="sr-only" for="id_{{ field.name }}" hidden>{{ field.label }}</label>
				    <input class="form-control"
				    	{% if field.field.widget.input_type == "password" %}
				    		type="password"
				    	{% else %}
				    		type="text"
				    	{% endif %}
				        placeholder="{{ field.label }}"
				        id="{{ field.name }}"
				        name="{{ field.name }}"
				        maxlength="{{ field.field.max_length }}"
				        {% if field.field.required %}
				        	required
				        {% endif %}
					> 

				{% endfor %}

		        <br>
		        <button class="btn btn-lg btn-primary btn-block" type="submit">Proceed</button>
		    </form>

	      <br>
		  
	      <center>
	      <a href="/" style="color:#FFF" style="font-size:1.5em" >Cancel</a>
	      </center>
		  

	</div>

	<div class="col-sm-4">
	</div>

</div>
</center>

login/templates/login/passwordResetActivation.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Magemi Mine Optimizer</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type = "text/css"/>
	<!--<meta name="viewport" content = "width=device-width, initial-scale=1.0">-->
	<meta name="viewport">
	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#FF6600" style="padding:40px">
<style="background-color:#FF6600">

<center>
<div class="row">

	<div class="col-sm-4">
	</div>

	<div class='col-sm-4'>
		<br>
		<br>

	      <form class="form-signin" role="form" action="{% url 'login:passwordResetActivation' %}" method="POST">
				{% csrf_token %}
				<center>
		        <h2 class="form-signup-heading" style="color:#FFF">Password Reset Activation</h2>
		        </center>
		        <br>

		        {% if errorMsg != None %}
		        	<center>
		        	<p>{{ errorMsg }}</p>
		        	</center>
		        {% endif %}

		        {% for field in form %}

				    <label class="sr-only" for="id_{{ field.name }}" hidden>{{ field.label }}</label>
				    <input class="form-control"
				    	{% if field.field.widget.input_type == "password" %}
				    		type="password"
				    	{% else %}
				    		type="text"
				    	{% endif %}
				        placeholder="{{ field.label }}"
				        id="{{ field.name }}"
				        name="{{ field.name }}"
				        maxlength="{{ field.field.max_length }}"
				        {% if field.field.required %}
				        	required
				        {% endif %}
					> 

				{% endfor %}

		        <br>
		        <button class="btn btn-lg btn-primary btn-block" type="submit">Proceed</button>
		    </form>

	      <br>
		  
	      <center>
	      <a href="/" style="color:#FFF" style="font-size:1.5em" >Cancel</a>
	      </center>
		  

	</div>

	<div class="col-sm-4">
	</div>

</div>
</center>

login/templates/login/success.html
{% include "home/header.html" %}

<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">
			<center>
		        <h2>You've successfully Logged in!</h2>
		    </center>
		    <center>
		    <a href="/home">Return to Homepage</a>
		    </center>
		</div>

		<div class="col-sm-2">
		</div>

</div>

{% include "home/footer.html" %}