setup/urls.py
from django.conf.urls import url
from . import views

app_name = 'setup'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^step2$', views.index2, name='index2'),
	url(r'^step3$', views.index3, name='index3'),
	url(r'^step4$', views.index4, name='index4'),
	url(r'^step5$', views.index5, name='index5'),
	url(r'^step6$', views.index6, name='index6'),
	url(r'^step7$', views.index7, name='index7'),
	url(r'^step8$', views.index8, name='index8'),
	url(r'^step9$', views.index9, name='index9'),
	url(r'^step10$', views.index10, name='index10')
]

setup/templates/setup/capex.html
{% include "home/header.html" %}

{% if minePlanRegistered is not None %}

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<form class="form-signup" role="form" action="{% url 'setup:index5' %}" method="POST">
				<center>
		        <h2 class="form-signup-heading">Declare CAPEX (in CAN$):</h2>
		        </center>
		        <br>
		        {% csrf_token %}

				<input type="hidden" value="{{ LOM }}" name="LOM" />

		        <br>
				<br>

		</div>

		<div class="col-sm-4">
		</div>

	</div>

	<div class="table-responsive">
  		<table class="table table-bordered">
    		<thead> 
    			<tr> 
    				<th>        </th>
                    <th>Year -3</th>
                    <th>Year -2</th>
                    <th>Year -1</th>
    				{% for i in "x"|rjust:LOM %}
    					<th>Year {{ forloop.counter0|add:"1" }}</th>
    				{% endfor %}
    			</tr> 
    		</thead>
    		<tbody>
    			<tr>
    				<th>Pre-Stripping</th>
                    <td><input id="id_year-3PreStripping" name="year-3PreStripping" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2PreStripping" name="year-2PreStripping" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1PreStripping" name="year-1PreStripping" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}PreStripping" name="year{{ forloop.counter0|add:'1' }}PreStripping" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Mining Equipment Initial</th>
                    <td><input id="id_year-3MiningEquipmentInitial" name="year-3MiningEquipmentInitial" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2MiningEquipmentInitial" name="year-2MiningEquipmentInitial" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1MiningEquipmentInitial" name="year-1MiningEquipmentInitial" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}MiningEquipmentInitial" name="year{{ forloop.counter0|add:'1' }}MiningEquipmentInitial" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Mining Equipment Sustaining</th>
                    <td><input id="id_year-3MiningEquipmentSustaining" name="year-3MiningEquipmentSustaining" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2MiningEquipmentSustaining" name="year-2MiningEquipmentSustaining" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1MiningEquipmentSustaining" name="year-1MiningEquipmentSustaining" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}MiningEquipmentSustaining" name="year{{ forloop.counter0|add:'1' }}MiningEquipmentSustaining" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Infrastructure Direct Costs</th>
                    <td><input id="id_year-3InfrastructureDirectCosts" name="year-3InfrastructureDirectCosts" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2InfrastructureDirectCosts" name="year-2InfrastructureDirectCosts" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1InfrastructureDirectCosts" name="year-1InfrastructureDirectCosts" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}InfrastructureDirectCosts" name="year{{ forloop.counter0|add:'1' }}InfrastructureDirectCosts" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Infrastructure Indirect Costs</th>
                    <td><input id="id_year-3InfrastructureIndirectCosts" name="year-3InfrastructureIndirectCosts" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2InfrastructureIndirectCosts" name="year-2InfrastructureIndirectCosts" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1InfrastructureIndirectCosts" name="year-1InfrastructureIndirectCosts" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}InfrastructureIndirectCosts" name="year{{ forloop.counter0|add:'1' }}InfrastructureIndirectCosts" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Contingency</th>
                    <td><input id="id_year-3Contingency" name="year-3Contingency" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2Contingency" name="year-2Contingency" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1Contingency" name="year-1Contingency" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}Contingency" name="year{{ forloop.counter0|add:'1' }}Contingency" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Railcars</th>
                    <td><input id="id_year-3Railcars" name="year-3Railcars" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2Railcars" name="year-2Railcars" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1Railcars" name="year-1Railcars" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}Railcars" name="year{{ forloop.counter0|add:'1' }}Railcars" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Other Mobile Equipment</th>
                    <td><input id="id_year-3OtherMobileEquipment" name="year-3OtherMobileEquipment" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2OtherMobileEquipment" name="year-2OtherMobileEquipment" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1OtherMobileEquipment" name="year-1OtherMobileEquipment" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}OtherMobileEquipment" name="year{{ forloop.counter0|add:'1' }}OtherMobileEquipment" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Closure and Rehab Assurance</th>
                    <td><input id="id_year-3ClosureAndRehabAssurancePayment" name="year-3ClosureAndRehabAssurancePayment" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2ClosureAndRehabAssurancePayment" name="year-2ClosureAndRehabAssurancePayment" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1ClosureAndRehabAssurancePayment" name="year-1ClosureAndRehabAssurancePayment" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}ClosureAndRehabAssurancePayment" name="year{{ forloop.counter0|add:'1' }}ClosureAndRehabAssurancePayment" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Deposits Provision Payment</th>
                    <td><input id="id_year-3DepositsProvisionPayment" name="year-3DepositsProvisionPayment" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2DepositsProvisionPayment" name="year-2DepositsProvisionPayment" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1DepositsProvisionPayment" name="year-1DepositsProvisionPayment" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}DepositsProvisionPayment" name="year{{ forloop.counter0|add:'1' }}DepositsProvisionPayment" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Working Capital</th>
                    <td><input id="id_year-3WorkingCapCurrentProd" name="year-3WorkingCapCurrentProd" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2WorkingCapCurrentProd" name="year-2WorkingCapCurrentProd" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1WorkingCapCurrentProd" name="year-1WorkingCapCurrentProd" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}WorkingCapCurrentProd" name="year{{ forloop.counter0|add:'1' }}WorkingCapCurrentProd" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Working Capital Stockpile Reclaim</th>
                    <td><input id="id_year-3WorkingCapCostsOfLG" name="year-3WorkingCapCostsOfLG" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2WorkingCapCostsOfLG" name="year-2WorkingCapCostsOfLG" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1WorkingCapCostsOfLG" name="year-1WorkingCapCostsOfLG" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}WorkingCapCostsOfLG" name="year{{ forloop.counter0|add:'1' }}WorkingCapCostsOfLG" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>EPCM</th>
                    <td><input id="id_year-3EPCM" name="year-3EPCM" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2EPCM" name="year-2EPCM" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1EPCM" name="year-1EPCM" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}EPCM" name="year{{ forloop.counter0|add:'1' }}EPCM" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    			<tr>
    				<th>Owner's Costs</th>
                    <td><input id="id_year-3OwnersCosts" name="year-3OwnersCosts" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-2OwnersCosts" name="year-2OwnersCosts" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
                    <td><input id="id_year-1OwnersCosts" name="year-1OwnersCosts" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% for i in "x"|rjust:LOM %}
    					<td><input id="id_year{{ forloop.counter0|add:'1' }}OwnersCosts" name="year{{ forloop.counter0|add:'1' }}OwnersCosts" placeholder="Max 2 Decimals" step="0.01" type="number" required=""></td>
    				{% endfor %}
    			</tr>
    		</tbody>
  		</table>
	</div>

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class="col-sm-4">
			<center>
			<button class="btn btn-group-lg btn-primary" type="button" onClick="history.go(-1);return true;">Back</button>
			<button class="btn btn-group-lg btn-primary" type="submit">Next</button>
			</form>
			</center>
			
		</div>
	

		<div class="col-sm-4">
		</div>

	</div>
	

{% else %}

<p>ERROR!</p>

{% endif %}

{% include "home/footer.html" %}

setup/templates/setup/commodity.html
{% include "home/header.html" %}

<form class="form-signup" role="form" action="{% url 'setup:index' %}" method="POST">

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

				<center>
		        <h2 class="form-signup-heading">Select Your Main Commodities:</h2>
		        </center>
		        <br>

		        {% if errorMsg != None %}
		        	<center>
		        	<p class="errorMsg" style="color:#FF6600">{{ errorMsg }}</p>
		        	</center>
		        {% endif %}
		        
		        {% csrf_token %}

		</div>

		<div class="col-sm-4">
		</div>

	</div>


	<div class="row">

		<div class="col-sm-4">
		<ul style="list-style: none;" id="id_{{ form.mainCommodity1.name }}">
 			{% for pk, choice in form.mainCommodity1.field.widget.choices %}
				<li>
					<label for="id_{{ form.mainCommodity1.name }}_{{ forloop.counter0 }}">
						<input {% for m2moption in model.m2moptions.all %}{% if option.pk == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.mainCommodity1.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.mainCommodity1.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</div>

		<div class="col-sm-4">
		<ul style="list-style: none;" id="id_{{ form.mainCommodity2.name }}">
 			{% for pk, choice in form.mainCommodity2.field.widget.choices %}
				<li>
					<label for="id_{{ form.mainCommodity2.name }}_{{ forloop.counter0 }}">
						<input {% for m2moption in model.m2moptions.all %}{% if option.pk == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.mainCommodity2.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.mainCommodity2.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</div>

		<div class="col-sm-4">
		<ul style="list-style: none;" id="id_{{ form.mainCommodity3.name }}">
 			{% for pk, choice in form.mainCommodity3.field.widget.choices %}
				<li>
					<label for="id_{{ form.mainCommodity3.name }}_{{ forloop.counter0 }}">
						<input {% for m2moption in model.m2moptions.all %}{% if option.pk == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.mainCommodity3.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.mainCommodity3.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</div>

	</div>



	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<!-- <form class="form-signup" role="form" action="{% url 'setup:index' %}" method="POST"> -->
				<center>
		        <h2 class="form-signup-heading">Select Your Deleterious Commodities:</h2>
		        </center>
		        <br>

		</div>

		<div class="col-sm-4">
		</div>

	</div>


	<div class="row">

		<div class="col-sm-4">
		<ul style="list-style: none;" id="id_{{ form.delCommodity1.name }}">
 			{% for pk, choice in form.delCommodity1.field.widget.choices %}
				<li>
					<label for="id_{{ form.delCommodity1.name }}_{{ forloop.counter0 }}">
						<input {% for m2moption in model.m2moptions.all %}{% if option.pk == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.delCommodity1.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.delCommodity1.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</div>

		<div class="col-sm-4">
		<ul style="list-style: none;" id="id_{{ form.delCommodity2.name }}">
 			{% for pk, choice in form.delCommodity2.field.widget.choices %}
				<li>
					<label for="id_{{ form.delCommodity2.name }}_{{ forloop.counter0 }}">
						<input {% for m2moption in model.m2moptions.all %}{% if option.pk == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.delCommodity2.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.delCommodity2.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</div>

		<div class="col-sm-4">
		<ul style="list-style: none;" id="id_{{ form.delCommodity3.name }}">
 			{% for pk, choice in form.delCommodity3.field.widget.choices %}
				<li>
					<label for="id_{{ form.delCommodity3.name }}_{{ forloop.counter0 }}">
						<input {% for m2moption in model.m2moptions.all %}{% if option.pk == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.delCommodity3.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.delCommodity3.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</div>

	</div>



	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class="col-sm-4">
			<button class="btn btn-lg btn-primary btn-block" type="submit">Next</button>
			</form>
			<!-- <button class="btn btn-lg btn-primary btn-block" type="button">Back</button> -->
		</div>

		<div class="col-sm-4">
		</div>

	</div>

	<br>
	<br>

{% include "home/footer.html" %}

setup/templates/setup/delCommodity.html
{% include "home/header.html" %}

{% if mainCommodityRegistered is not None %}

<form class="form-signup" role="form" action="{% url 'setup:index2' %}" method="POST">

	<div class="row">
	<centre>

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<!-- <form class="form-signup" role="form" action="{% url 'setup:index' %}" method="POST"> -->
				<center>
		        <h2 class="form-signup-heading">Select Your Deleterious Commodities:</h2>
		        </center>
		        <br>

		        {% if errorMsg != None %}
		        	<center>
		        	<p class="errorMsg" style="color:#FF6600">{{ errorMsg }}</p>
		        	</center>
		        {% endif %}
		        
		        {% csrf_token %}

		</div>

		<div class="col-sm-4">
		</div>

	</div>


	<div class="row">

		<div class="col-sm-4">
		<center>
		<ul style="list-style: none;" id="id_{{ form.commodity1.name }}">
 			{% for pk, choice in form.commodity1.field.widget.choices %}
				<li>
					<label for="id_{{ form.commodity1.name }}_{{ forloop.counter0 }}">
						<input {% for m2moption in model.m2moptions.all %}{% if option.pk == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.commodity1.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.commodity1.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</center>
		</div>

		<div class="col-sm-4">
		<center>
		<ul style="list-style: none;" id="id_{{ form.commodity2.name }}">
 			{% for pk, choice in form.commodity2.field.widget.choices %}
				<li>
					<label for="id_{{ form.commodity2.name }}_{{ forloop.counter0 }}">
						<input {% for m2moption in model.m2moptions.all %}{% if option.pk == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.commodity2.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.commodity2.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</center>
		</div>

		<div class="col-sm-4">
		<center>
		<ul style="list-style: none;" id="id_{{ form.commodity3.name }}">
 			{% for pk, choice in form.commodity3.field.widget.choices %}
				<li>
					<label for="id_{{ form.commodity3.name }}_{{ forloop.counter0 }}">
						<input {% for m2moption in model.m2moptions.all %}{% if option.pk == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_{{ form.commodity3.name }}_{{ forloop.counter0 }}" value="{{ pk }}" name="{{ form.commodity3.name }}" />
						{{ choice }}
					</label>
				</li>
			{% endfor %}
		</ul>
		</center>
		</div>

	</div>


	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class="col-sm-4">
			<center>
			<button class="btn btn-group-lg btn-primary" type="button" onClick="history.go(-1);return true;">Back</button>
			<button class="btn btn-group-lg btn-primary" type="submit">Next</button>
			</form>
			</center>			
		</div>	

		<div class="col-sm-4">
		</div>
	
	</center>
	</div>

{% else %}

<p>ERROR!</p>

{% endif %}

{% include "home/footer.html" %}

setup/templates/setup/financials.html
{% include "home/header.html" %}

{% if smelterRegistered is not None %}

	<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">
			<br>
			<br>

			<form class="form-signup" role="form" action="{% url 'setup:index8' %}" method="POST">
				<center>
		        <h2 class="form-signup-heading">Declare Prices (US$/t):</h2>
		        </center>
		        <br>
		        {% csrf_token %}

				<div class="table-responsive">
					<table class="table table-bordered">
						<thead> 
                			<tr> 
                    			<th>        </th>
                    			<th>Lump Price</th>
                    			<th>Lump Premium</th>
                    			<th>Fines Price</th>
                    			<th>Ultra Fines Price</th>
                    			<th>Lump Average</th>
                			</tr> 
           				</thead>
           				<tbody>
           				{% for curr in numStockpiles %}
           					<tr>
           						<th>Stockpile {{ curr }}</th>
           						<td>
           							<input id="id_Stockpile{{ curr }}Lump" name="Stockpile{{ curr }}Lump" placeholder="Max 2 Decmial Places" step="0.01" type="number" required="">
           						</td>
	           					<td>
	           						<input id="id_Stockpile{{ curr }}LumpPrem" name="Stockpile{{ curr }}LumpPrem" placeholder="Max 2 Decmial Places" step="0.01" type="number" required="">
	           					</td>
	           					<td>
	           						<input id="id_Stockpile{{ curr }}Fines" name="Stockpile{{ curr }}Fines" placeholder="Max 2 Decmial Places" step="0.01" type="number" required="">
	           					</td>
	           					<td>
	           						<input id="id_Stockpile{{ curr }}UltraFines" name="Stockpile{{ curr }}UltraFines" placeholder="Max 2 Decmial Places" step="0.01" type="number" required="">
	           					</td>
	           					<td>
	           						<input id="id_Stockpile{{ curr }}LumpAvg" name="Stockpile{{ curr }}LumpAvg" placeholder="Max 2 Decmial Places" step="0.01" type="number" required="">
	           					</td>
           					</tr>
           				{% endfor %}	
           				</tbody>
					</table>
				</div>

				<center>
				<button class="btn btn-group-lg btn-primary" type="button" onClick="history.go(-1);return true;">Back</button>
				<button class="btn btn-group-lg btn-primary" type="submit">Next</button>
				</form>
				</center>
			</form>
		 
		</div>

		<div class="col-sm-2">
		</div>

	</div>

{% else %}

<p>ERROR!</p>

{% endif %}

{% include "home/footer.html" %}

setup/templates/setup/inputs.html
{% include "home/header.html" %}

{% if taxesRegistered is not None %}

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<form class="form-signup" role="form" action="{% url 'setup:index10' %}" method="POST">
				<center>
		        <h2 class="form-signup-heading">Declare Other Inputs:</h2>
		        </center>
		        <br>
		        {% csrf_token %}

				<div class="table-responsive">
					<table class="table table-condensed">
					{{ form.as_table }}
					</table>
				</div>
			
			<br>
			<br>

			<center>
			<button class="btn btn-group-lg btn-primary" type="button" onClick="history.go(-1);return true;">Back</button>
			<button class="btn btn-group-lg btn-primary" type="submit">Next</button>
			</form>
			</center>

		</div>

		<div class="col-sm-4">
		</div>

	</div>

{% else %}

<p>ERROR!</p>

{% endif %}

{% include "home/footer.html" %}

setup/templates/setup/success.html
{% include "home/header.html" %}

<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">
			<center>
		        <h2>Setup Success!</h2>
		    </center>
		    <center>
		    <a href="/home">Return to Homepage</a>
		    </center>
		</div>

		<div class="col-sm-2">
		</div>

</div>

{% include "home/footer.html" %}