signup/urls.py
from django.conf.urls import url
from . import views
from .forms import companyForm, mineForm, signUpForm

app_name = 'signup'

# FORMS = [("company", companyForm),
# 		 ("mine", mineForm),
# 		 ("user", signUpForm)]

# FORMS = [companyForm, mineForm, signUpForm]

urlpatterns = [
	url(r'^$', views.registerCompany, name='registerCompany'),
	url(r'^step2$', views.registerMine, name='registerMine'),
	url(r'^step3$', views.registerUser, name='registerUser'),
	# url(r'^$', views.SignupWizard.as_view(FORMS)),
]

signup/templates/signup/block_signup.html
{% extends "signup/block_wizard.html" %}

{% block form_if %}{% block form_else %}

	<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">	
			<div class="progress">
			  <div class="progress-bar progress-bar-info" style="width: 33.3%">
			    Step 1 of 3
			  </div>
			  <!-- <div class="progress-bar progress-bar-warning progress-bar-striped" style="width: 33.3%">
			    <span class="sr-only">Step 2 of 3 (danger)</span>
			  </div>
			  <div class="progress-bar progress-bar-danger" style="width: 33.3%">
			    <span class="sr-only">Step 3 of 3 (danger)</span>
			  </div> -->
			</div>
		</div>

		<div class="col-sm-2">
		</div>

	</div>

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

				<center>
		        <h2 class="form-signup-heading">Company Info</h2>
		        </center>
		        <br>

		        {% for field in form %}

				    <label class="control-label" for="id_{{ field.name }}" hidden>{{ field.label }}</label>
				    <input type="text" class="form-control"
				        placeholder="{{ field.label }}"
				        id="{{ field.name }}"
				        name="{{ field.name }}"
				        maxlength="{{ field.field.max_length }}"
				        {% if field.field.required %}
				        	required
				        {% endif %}
					>

				{% endfor %}
<!-- 				<br>
				<input class="btn btn-lg btn-primary btn-block" type="submit" value="Next"> -->

{% endblock %}{% endblock %} 

				<!-- {{ form.as_p }} -->

signup/templates/signup/block_signup2.html
{% extends "signup/block_wizard.html" %}

{% block form_if %}{% block form_else %}

	<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">	
			<div class="progress">
			  <div class="progress-bar progress-bar-info" style="width: 33.3%">
			    Step 1 of 3
			  </div>
			  <div class="progress-bar progress-bar-info" style="width: 33.3%">
			    Step 2 of 3
			  </div>
			  <!-- <div class="progress-bar progress-bar-danger" style="width: 33.3%">
			    <span class="sr-only">Step 3 of 3 (danger)</span>
			  </div> -->
			</div>
		</div>

		<div class="col-sm-2">
		</div>

	</div>

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

				<center>
		        <h2 class="form-signup-heading">Mine Info</h2>
		        </center>
		        <br>

		        {% for field in form %}

				    <label class="control-label" for="id_{{ field.name }}" hidden>{{ field.label }}</label>
				    <input type="text" class="form-control"
				        placeholder="{{ field.label }}"
				        id="{{ field.name }}"
				        name="{{ field.name }}"
				        maxlength="{{ field.field.max_length }}"
				        {% if field.field.required %}
				        	required
				        {% endif %}
					> 

				{% endfor %}
<!-- 				<br>
				<input class="btn btn-lg btn-primary btn-block" type="submit" value="Next"> -->

{% endblock %}{% endblock %}

signup/templates/signup/block_signup3.html
{% extends "signup/block_wizard.html" %}

{% block form_if %}{% block form_else %}

	<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">	
			<div class="progress">
			  <div class="progress-bar progress-bar-info" style="width: 33.3%">
			    Step 1 of 3
			  </div>
			  <div class="progress-bar progress-bar-info" style="width: 33.3%">
			    Step 2 of 3
			  </div>
			  <div class="progress-bar progress-bar-info" style="width: 33.3%">
			    Step 3 of 3
			  </div>
			</div>
		</div>

		<div class="col-sm-2">
		</div>

	</div>

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

				<center>
		        <h2 class="form-signup-heading">User Info</h2>
		        </center>
		        <br>

		        {% for field in form %}

				    <label class="control-label" for="id_{{ field.name }}" hidden>{{ field.label }}</label>
				    <input class="form-control"
				    	{% if field.field.widget.input_type == "password" %}
				    		type="password"
				    	{% else %}
				    		type="text"
				    	{% endif %}
				        placeholder="{{ field.label }}"
				        id="{{ field.name }}"
				        name="{{ field.name }}"
				        maxlength="{{ field.field.max_length }}"
				        {% if field.field.required %}
				        	required
				        {% endif %}
					> 

				{% endfor %}
<!-- 				<br>
				<input class="btn btn-lg btn-primary btn-block" type="submit" value="Next"> -->

{% endblock %}{% endblock %}

signup/templates/signup/block_wizard.html
{% include "home/header.html" %}

    <br>
            <form enctype="multipart/form-data" action="/signup/" method="post">{% csrf_token %}
                <table>
                    {{ wizard.management_form }}
                    {% if wizard.form.forms %}
                        {{ wizard.form.management_form }}
                        {% for form in wizard.form.forms %}
                            <!-- block below accesses -a customized form layout for each step -->
                            {% block form_if %}{% endblock %}
                        {% endfor %}
                    {% else %}
                        <!-- block below accesses a customized form layout for each step -->
                        <!-- using the with statement makes it possible to use the same layout used in the form_if block -->
                        {% with form=wizard.form %}
                        {% block form_else %}{% endblock %}
                        {% endwith %}
                    {% endif %}
                </table>
                {% if wizard.steps.prev %}
                <button name="wizard_goto_step" value="{{ wizard.steps.first }}" class="button">first step</button>
                <button name="wizard_goto_step" value="{{ wizard.steps.prev }}" class="button">prev step</button>
                {% endif %}

                <br>
                <input class="btn btn-lg btn-primary btn-block" type="submit" value="Next">
            </form>
            <br>
            <center>
                <a href="/">Cancel</a>
            </center>

        </div>

        <div class="col-sm-4">
        </div>

    </div>

{% include "home/footer.html" %}

signup/templates/signup/error.html
{% include "home/header.html" %}

<p>Error</p>

{% include "home/footer.html" %}

signup/templates/signup/signup.html
{% include "home/header.html" %}

	<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">	
			<div class="progress">
			  <div class="progress-bar progress-bar-info" style="width: 33.3%">
			    Step 1 of 3
			  </div>
			  <!-- <div class="progress-bar progress-bar-warning progress-bar-striped" style="width: 33.3%">
			    <span class="sr-only">Step 2 of 3 (danger)</span>
			  </div>
			  <div class="progress-bar progress-bar-danger" style="width: 33.3%">
			    <span class="sr-only">Step 3 of 3 (danger)</span>
			  </div> -->
			</div>
		</div>

		<div class="col-sm-2">
		</div>

	</div>

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<form class="form-signup" role="form" action="{% url 'signup:registerCompany' %}" method="POST">
				<center>
		        <h2 class="form-signup-heading">Company Info</h2>
		        </center>
		        <br>
		        {% csrf_token %}

		        {% for field in form %}

				    <label class="control-label" for="id_{{ field.name }}" hidden>{{ field.label }}</label>
				    <input type="text" class="form-control"
				        placeholder="{{ field.label }}"
				        id="{{ field.name }}"
				        name="{{ field.name }}"
				        maxlength="{{ field.field.max_length }}"
				        {% if field.field.required %}
				        	required
				        {% endif %}
					> 

				{% endfor %}

				<!-- {{ form.as_p }} -->

		        <br>
		        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Next">
		    </form>

		    <br>
		    <center>
		    	<a href="/home">Cancel</a>
		    </center>

		</div>

		<div class="col-sm-4">
		</div>

	</div>

{% include "home/footer.html" %}

signup/templates/signup/signup2.html
{% include "home/header.html" %}

{% if company_registered != None %}

    <!-- <p>value of company ID: {{ companyID }} </p> -->

	<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">	
			<div class="progress">
			  <div class="progress-bar progress-bar-info" style="width: 33.3%">
			    Step 1 of 3
			  </div>
			  <div class="progress-bar progress-bar-info" style="width: 33.3%">
			    Step 2 of 3
			  </div>
			  <!-- <div class="progress-bar progress-bar-danger" style="width: 33.3%">
			    <span class="sr-only">Step 3 of 3 (danger)</span>
			  </div> -->
			</div>
		</div>

		<div class="col-sm-2">
		</div>

	</div>

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<form class="form-signup" role="form" action="{% url 'signup:registerMine' %}" method="POST">
				<center>
		        <h2 class="form-signup-heading">Mine Info</h2>
		        </center>
		        <br>
		        {% csrf_token %}

		        {% for field in form %}

				    <label class="control-label" for="id_{{ field.name }}" hidden>{{ field.label }}</label>
				    <input type="text" class="form-control"
				        placeholder="{{ field.label }}"
				        id="{{ field.name }}"
				        name="{{ field.name }}"
				        maxlength="{{ field.field.max_length }}"
				        {% if field.field.required %}
				        	required
				        {% endif %}
					> 

				{% endfor %}

					<input type="hidden" value="{{ companyID }}" name="companyID" />

		        <br>
		        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Next">
		    </form>

		    <br>
		    <center>
		    	<a href="/home">Cancel</a>
		    </center>

		</div>

		<div class="col-sm-4">
		</div>

	</div>

{% else %}

<p>ERROR!</p>

{% endif %}

{% include "home/footer.html" %}

signup/templates/signup/signup3.html
{% include "home/header.html" %}

{% if mine_registered != None %}

<!-- 	<p>value of company ID: {{ companyID }} </p>
	<p>value of mine ID: {{ mineID }} </p> -->

	<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">	
			<div class="progress">
			  <div class="progress-bar progress-bar-info" style="width: 33.3%">
			    Step 1 of 3
			  </div>
			  <div class="progress-bar progress-bar-info" style="width: 33.3%">
			    Step 2 of 3
			  </div>
			  <div class="progress-bar progress-bar-info" style="width: 33.3%">
			    Step 3 of 3
			  </div>
			</div>
		</div>

		<div class="col-sm-2">
		</div>

	</div>

	<div class="row">

		<div class="col-sm-4">
		</div>

		<div class='col-sm-4'>
			<br>
			<br>

			<form class="form-signup" role="form" action="{% url 'signup:registerUser' %}" method="POST">
				<center>
		        <h2 class="form-signup-heading">User Info</h2>
		        </center>
		        <br>
		        {% csrf_token %}

		        {% if errorMsg != None %}
		        	<center>
		        	<p>{{ errorMsg }}</p>
		        	</center>
		        {% endif %}

		        {% for field in form %}

				    <label class="control-label" for="id_{{ field.name }}" hidden>{{ field.label }}</label>
				    <input class="form-control"
				    	{% if field.field.widget.input_type == "password" %}
				    		type="password"
				    	{% else %}
				    		type="text"
				    	{% endif %}
				        placeholder="{{ field.label }}"
				        id="{{ field.name }}"
				        name="{{ field.name }}"
				        maxlength="{{ field.field.max_length }}"
				        {% if field.field.required %}
				        	required
				        {% endif %}
					> 

				{% endfor %}

				<input type="hidden" value="{{ companyID }}" name="companyID" />
				<input type="hidden" value="{{ mineID }}" name="mineID" />

		        <br>
		        <button class="btn btn-lg btn-primary btn-block" type="submit">Next</button>
		    </form>

		    <br>
		    <center>
		    	<a href="/home">Cancel</a>
		    </center>

		</div>

		<div class="col-sm-4">
		</div>

	</div>

{% else %}

	<p>ERROR!</p>

{% endif %}

{% include "home/footer.html" %}

signup/templates/signup/success.html
{% include "home/header.html" %}

<div class="row">

		<div class="col-sm-2">
		</div>

		<div class="col-sm-8">
			<center>
		        <h2>Signup Success!</h2>
		    </center>
		    <center>
		    <a href="/home">Return to Homepage</a>
		    </center>
		</div>

		<div class="col-sm-2">
		</div>

</div>

{% include "home/footer.html" %}